### ISSUE TITLE
help + sync up

### ISSUE THREAD

**Issue by yawnt** [open-ndc/ndc-sandbox#1]
Hey!

We're the italian guys you met in Hamburg at the THack hackathon :)
I think it'd be cool to collaborate on this and explore how we can help, is there a place you guys use to discuss technical stuff?
Cheers!

**Comment by xurde** [comment]
Hey, @yawnt 
Sure thing. It would be great to have some help on board for this project!
Also some other points of view. :)

Do you use Gitter?
Maybe it could be a good starting point if I enable it to chat a bit about the plans here.

Cheers!

**Comment by yawnt** [comment]
gitter works for me, fire it up!

**Comment by xurde** [comment]
Done!

See you here.
https://gitter.im/open-ndc/chat
