### ISSUE TITLE
Not Found Response from ndc-Sandbox

### ISSUE THREAD

**Issue by skuladeep24** [open-ndc/ndc-sandbox#48]
I have setup the ndc-sandbox on my windows 7 laptop and trigged the api using an NDC compliant Airshopping request.xml.  "Not Found" is the response.  I see my request in the Server console. And the error information in the server console is pasted below. Could you please help me resolve this issue. Many Thanks.

---

Error in server console:-

---

I, [2016-09-20T17:10:03.125186 #13284]  INFO -- : Response: 404
I, [2016-09-20T17:10:03.126186 #13284]  INFO -- : Headers: {"Content-Type"=>"tex
t/html", "X-Cascade"=>"pass", "Vary"=>"Origin"}
I, [2016-09-20T17:10:03.126186 #13284]  INFO -- : Response:
I, [2016-09-20T17:10:03.127186 #13284]  INFO -- : Not Found
127.0.0.1 - - [20/Sep/2016:17:10:03 +0530] "POST /api/v0/ndc HTTP/1.1" 404 - 0.0
140
127.0.0.1 - - [20/Sep/2016:17:10:03 +0530] "POST /api/v0/ndc HTTP/1.1" 404 - 0.0
160

**Comment by xurde** [comment]
Hi @skuladeep24 
Are you positive you are sending some data in the POST request?

**Comment by skuladeep24** [comment]
@xurde Yes. Attached is the file(extn changed to .txt) I used in the call. I could see my request reaching the servers's console too.

Our call was exactly as mentioned in Github:-
curl -X POST "http://localhost:9292/api/v0/ndc" -H "Content-Type: application/xml" --data @AirShopping.xml

[AirShopping.txt](https://github.com/open-ndc/ndc-sandbox/files/484261/AirShopping.txt)

**Comment by xurde** [comment]
@skuladeep24 
Sorry, our bad. There is a problem on curl command params order.
It should be like this:
`curl -X POST -H "Content-Type: application/xml" --data @AirShopping.xml "http://ndc-sandbox.dev/api/ndc/"`

We'll fix if right now on README.

Thanks!

**Comment by skuladeep24** [comment]
@xurde  Thank you. 
   I am facing a different error now. errors are attached. One file has the errors that were captured in the servers console and the other  is the response i received on curl call.
[Error-Open-NDC.txt](https://github.com/open-ndc/ndc-sandbox/files/485466/Error-Open-NDC.txt)
[Error-Open-NDC.txt](https://github.com/open-ndc/ndc-sandbox/files/485469/Error-Open-NDC.txt)
[Response.txt](https://github.com/open-ndc/ndc-sandbox/files/485470/Response.txt)

here is my call:
  curl -X POST -H "Content-Type: application/xml" --data @AirShopping.xml "http://ndc-sandbox.dev/api/ndc/"

**Comment by xurde** [comment]
@skuladeep24 Hi again!
Have you properly setup a DB (Postgres by default), run migrations and loaded fixtures in the DB?
Also, AirShopping query has to be accordingly made with fixtures loaded in DB (airlines, routes, etc).

**Comment by skuladeep24** [comment]
@xurde. I just followed the instructions in the readme file.  I couldnt do any of the activities((run migrations,load fixtures in the DB, etc) mentioned by you. It would be great if those instructions are included too. Many Thanks

**Comment by skuladeep24** [comment]
@xurde Thank you. we could setup the server as per your instructions. We could get proper response for Airshopping. we are now trying OrderCreate and Order retrieve operations. We see that the db schemas which are related to order, seat availibility etc are missing in schemas.rb file. Could you please suggest on how to proceed.

**Comment by xurde** [comment]
Hi @skuladeep24 

I'm glad it worked for you. Let me close this issue.

Regarding ordering capabilities, you are right. They are not yet implemented, but since we managed to make offer persistent (using Redis), I think it shouldn't be too much work at least implement OrderCreate request. Could you help a bit on this?
I'm happy to orient here on a Skype call.

Cheers.

**Comment by skuladeep24** [comment]
Hi @xurde  Thank you. We are new to Ruby. Please let me know if there are any prerequisites for this effort. We would be happy to contribute. 
Kuladeep

**Comment by xurde** [comment]
@skuladeep24 Please, check the email in your profile. :)
